BEGIN;

CREATE TABLE IF NOT EXISTS item (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR(64) NOT NULL UNIQUE,
    item_name VARCHAR(500),
    unit VARCHAR(255),
    item_group VARCHAR(255),
    item_category VARCHAR(255),
    sara_eligible BOOLEAN
);

COMMENT ON COLUMN item.sara_eligible IS
    'NULL means not yet verified. Populate only from a documented SARA source.';
CREATE TABLE IF NOT EXISTS premise (
    premise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premise_code VARCHAR(64) NOT NULL UNIQUE,
    premise_name VARCHAR(500),
    address VARCHAR,
    district VARCHAR(255),
    state VARCHAR(255),
    google_place_id VARCHAR(255),
    place_match_refreshed_at TIMESTAMPTZ,
    sara_partner BOOLEAN,
    sara_match_candidate BOOLEAN NOT NULL DEFAULT FALSE
);

-- Keep local databases aligned when this idempotent schema is reapplied.
ALTER TABLE item
    DROP COLUMN IF EXISTS sara_verified_date;
ALTER TABLE premise
    DROP COLUMN IF EXISTS place_match_status,
    DROP COLUMN IF EXISTS place_match_confidence,
    DROP COLUMN IF EXISTS sara_verified_date;
ALTER TABLE premise
    ADD COLUMN IF NOT EXISTS sara_match_candidate BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN premise.google_place_id IS
    'Top candidate enrichment; PriceCatcher does not publish a Google Place ID.';
COMMENT ON COLUMN premise.sara_partner IS
    'NULL means not yet verified. Populate only from a documented SARA source.';
COMMENT ON COLUMN premise.sara_match_candidate IS
    'TRUE means the PriceCatcher and SARA rows form a strict automated one-to-one shared-top-Place-ID candidate. FALSE does not mean non-partner.';

CREATE TABLE IF NOT EXISTS current_status (
    item_id BIGINT NOT NULL,
    premise_id BIGINT NOT NULL,
    current_price NUMERIC(12, 2) NOT NULL,
    price_observed_date DATE NOT NULL,
    price_synced_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    out_of_stock_report_count INTEGER NOT NULL DEFAULT 0,
    report_count_date DATE,
    status_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (item_id, premise_id),
    CONSTRAINT current_status_item_fk
        FOREIGN KEY (item_id) REFERENCES item (item_id),
    CONSTRAINT current_status_premise_fk
        FOREIGN KEY (premise_id) REFERENCES premise (premise_id),
    CONSTRAINT current_status_price_positive CHECK (current_price > 0),
    CONSTRAINT current_status_report_count_nonnegative
        CHECK (out_of_stock_report_count >= 0)
);

COMMENT ON TABLE current_status IS
    'Latest observed PriceCatcher price for each item-premise pair plus separate unverified stock-report signals.';
COMMENT ON COLUMN current_status.price_observed_date IS
    'Date the source observed the price; this is not proof of current stock.';
COMMENT ON COLUMN current_status.price_synced_at IS
    'Timestamp at which SmartCart ingested the source observation.';
COMMENT ON COLUMN current_status.out_of_stock_report_count IS
    'Count of recent anonymous reports; reports are unverified signals, not stock facts.';

CREATE INDEX IF NOT EXISTS premise_location_idx
    ON premise (state, district);
CREATE INDEX IF NOT EXISTS current_status_observed_date_idx
    ON current_status (price_observed_date DESC);
CREATE INDEX IF NOT EXISTS current_status_premise_idx
    ON current_status (premise_id);

COMMIT;
