BEGIN;

CREATE TABLE IF NOT EXISTS item (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR(64) NOT NULL UNIQUE,
    item_name VARCHAR(500),
    unit VARCHAR(255),
    item_group VARCHAR(255),
    item_category VARCHAR(255),
    sara_eligible BOOLEAN,
    quantity_value NUMERIC(12, 4),
    quantity_unit VARCHAR(8)
);

-- Idempotent upgrade for databases created before the pack-ratio columns
-- existed (US 3.2): quantity_value is stored in the base unit (kg or litre),
-- quantity_unit is the normalised family 'KG' or 'L'. NULL = not comparable.
ALTER TABLE item ADD COLUMN IF NOT EXISTS quantity_value NUMERIC(12, 4);
ALTER TABLE item ADD COLUMN IF NOT EXISTS quantity_unit VARCHAR(8);

COMMENT ON COLUMN item.sara_eligible IS
    'NULL means not yet verified. Populate only from a documented SARA source.';
CREATE TABLE IF NOT EXISTS premise (
    premise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premise_code VARCHAR(64) NOT NULL UNIQUE,
    premise_name VARCHAR(500),
    address VARCHAR,
    district VARCHAR(255),
    state VARCHAR(255),
    google_place_id VARCHAR(255),
    place_match_refreshed_at TIMESTAMPTZ,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_provider VARCHAR(32),
    location_refreshed_at TIMESTAMPTZ,
    sara_partner BOOLEAN,
    sara_match_candidate BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT premise_latitude_range
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT premise_longitude_range
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT premise_coordinate_pair
        CHECK ((latitude IS NULL) = (longitude IS NULL))
);

-- Keep local databases aligned when this idempotent schema is reapplied.
ALTER TABLE item
    DROP COLUMN IF EXISTS sara_verified_date;
ALTER TABLE premise
    DROP COLUMN IF EXISTS place_match_status,
    DROP COLUMN IF EXISTS place_match_confidence,
    DROP COLUMN IF EXISTS sara_verified_date;
ALTER TABLE premise
    ADD COLUMN IF NOT EXISTS sara_match_candidate BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS location_provider VARCHAR(32),
    ADD COLUMN IF NOT EXISTS location_refreshed_at TIMESTAMPTZ;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'premise_latitude_range'
    ) THEN
        ALTER TABLE premise ADD CONSTRAINT premise_latitude_range
            CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'premise_longitude_range'
    ) THEN
        ALTER TABLE premise ADD CONSTRAINT premise_longitude_range
            CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'premise_coordinate_pair'
    ) THEN
        ALTER TABLE premise ADD CONSTRAINT premise_coordinate_pair
            CHECK ((latitude IS NULL) = (longitude IS NULL));
    END IF;
END
$$;

COMMENT ON COLUMN premise.google_place_id IS
    'Top candidate enrichment; PriceCatcher does not publish a Google Place ID.';
COMMENT ON COLUMN premise.latitude IS
    'Routing prefilter coordinate from location_provider; refresh or remove according to provider terms.';
COMMENT ON COLUMN premise.longitude IS
    'Routing prefilter coordinate from location_provider; refresh or remove according to provider terms.';
COMMENT ON COLUMN premise.location_refreshed_at IS
    'Time the provider coordinate was refreshed. The recommendation query excludes stale coordinates.';
COMMENT ON COLUMN premise.sara_partner IS
    'NULL means not yet verified. Populate only from a documented SARA source.';
COMMENT ON COLUMN premise.sara_match_candidate IS
    'TRUE means the PriceCatcher and SARA rows form a strict automated one-to-one shared-top-Place-ID candidate. FALSE does not mean non-partner.';

CREATE TABLE IF NOT EXISTS current_status (
    item_id BIGINT NOT NULL,
    premise_id BIGINT NOT NULL,
    current_price NUMERIC(12, 2) NOT NULL,
    price_observed_date DATE NOT NULL,
    price_synced_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    out_of_stock_report_count INTEGER NOT NULL DEFAULT 0,
    report_count_date DATE,
    status_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (item_id, premise_id),
    CONSTRAINT current_status_item_fk
        FOREIGN KEY (item_id) REFERENCES item (item_id),
    CONSTRAINT current_status_premise_fk
        FOREIGN KEY (premise_id) REFERENCES premise (premise_id),
    CONSTRAINT current_status_price_positive CHECK (current_price > 0),
    CONSTRAINT current_status_report_count_nonnegative
        CHECK (out_of_stock_report_count >= 0)
);

COMMENT ON TABLE current_status IS
    'Latest observed PriceCatcher price for each item-premise pair plus separate unverified stock-report signals.';
COMMENT ON COLUMN current_status.price_observed_date IS
    'Date the source observed the price; this is not proof of current stock.';
COMMENT ON COLUMN current_status.price_synced_at IS
    'Timestamp at which SmartCart ingested the source observation.';
COMMENT ON COLUMN current_status.out_of_stock_report_count IS
    'Count of recent anonymous reports; reports are unverified signals, not stock facts.';

CREATE INDEX IF NOT EXISTS premise_location_idx
    ON premise (state, district);
CREATE INDEX IF NOT EXISTS premise_coordinates_idx
    ON premise (latitude, longitude)
    WHERE latitude IS NOT NULL AND longitude IS NOT NULL;
CREATE INDEX IF NOT EXISTS current_status_observed_date_idx
    ON current_status (price_observed_date DESC);
CREATE INDEX IF NOT EXISTS current_status_premise_idx
    ON current_status (premise_id);

COMMIT;
